### ISSUE TITLE
Apply for json files as well

### ISSUE THREAD

**Issue by gerazov** [neoclide/jsonc.vim#7]
It would be useful to add the option to apply this for `*.json` files as well, or at least document how to in the Readme.

I did it via including this in my `init.vim` as suggested [here](https://www.reddit.com/r/neovim/comments/lx4anr/autocmd_au_filetype_au_bufreadpre_etc_doesnt_work/):
```vim
autocmd BufRead,BufNewFile *.json set filetype=jsonc
```

**Comment by sisrfeng** [comment]
But  comment in json files should be highlighted as error,  while jsonc not

**Comment by gerazov** [comment]
Yeah ... but people nowadays just add them anyhow :sweat_smile: 

Maybe add this as an optional feature, or just tell people how to do it in the `README`?

**Comment by sisrfeng** [comment]
I compared neoclide/jsonc.vim with nvim0.7's official  syntax/jsonc.ivm,  find that the official one is updated and more similar to vim-json, so I don't use neoclide/jsonc.vim  now

**Comment by gerazov** [comment]
Ok, good info :+1:
